name: MIKAMONLINE
favicon: null
layout_spectrum: 0.5540906977839768
typography_spectrum: 0.7389001501724124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8b6a9'
    - '#ab9997'
    - '#cbdde1'
    - '#9d695b'
    - '#452925'
  brandStrength: 0.9207164959516376
  lightness: 0.43727512820623815
  saturation: 0
  rhythmicContrast: 0.26805396704003215
purpose: []
